# Analysis of Canadian Immigration Data

*This project is part of my data analytics learning journey, combining my background in immigration with data analysis skills.*

The goal is to understand patterns, distribution, and key findings about immigration over time.

## 1. Importing Libraries

Importing the main libraries used for data analysis and visualization.

In [155]:
import pandas as pd
import plotly.express as px

## 2. Loading the dataset

Loading the dataset into a pandas DataFrame.

In [156]:
df = pd.read_csv('../canadian_immigration_data.csv')

## 3. Initial Data Analysis

Analyzing the first few rows to understand the structure of the dataset.

In [157]:
df.head()

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15

## 4. Dataset Structure

Checking the data types and overall structure of the dataset.

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    195 non-null    object
 1   Continent  195 non-null    object
 2   Region     195 non-null    object
 3   DevName    195 non-null    object
 4   1980       195 non-null    int64
 5   1981       195 non-null    int64
 6   1982       195 non-null    int64
 7   1983       195 non-null    int64
 8   1984       195 non-null    int64
 9   1985       195 non-null    int64
 10  1986       195 non-null    int64
 11  1987       195 non-null    int64
 12  1988       195 non-null    int64
 13  1989       195 non-null    int64
 14  1990       195 non-null    int64
 15  1991       195 non-null    int64
 16  1992       195 non-null    int64
 17  1993       195 non-null    int64
 18  1994       195 non-null    int64
 19  1995       195 non-null    int64
 20  1996       195 non-null    int64
 21  1997       195 non-null    int64
 22  1998       195 non-null    int64
 23  1999       195 non-null    int64
 24  2000       195 non-null    int64
 25  2001       195 non-null    int64
 26  2002       195 non-null    int64
 27  2003       195 non-null    int64
 28  2004       195 non-null    int64
 29  2005       195 non-null    int64
 30  2006       195 non-null    int64
 31  2007       195 non-null    int64
 32  2008       195 non-null    int64
 33  2009       195 non-null    int64
 34  2010       195 non-null    int64
 35  2011       195 non-null    int64
 36  2012       195 non-null    int64
 37  2013       195 non-null    int64
 38  Total      195 non-null    int64
dtypes: int64(35), object(4)
memory usage: 59.5+ KB

### Creating formatted labels for visualization

Some country names are too long and affect the readability of visualizations.  
To improve clarity, a shortened version of country names will be created for display purposes.

In [159]:
df['Country_short'] = df['Country'].replace({
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'Iran (Islamic Republic of)': 'Iran'
})

## 5. Descriptive Statistics

Understanding the distribution and central tendencies of numerical columns.

In [160]:
df.describe()

,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
count,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,...,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000,195.000000
mean,508.394872,566.989744,534.723077,387.435897,376.497436,358.861538,441.271795,691.133333,714.389744,843.241026,...,1320.292308,1266.958974,1191.820513,1246.394872,1275.733333,1420.287179,1262.533333,1313.958974,1320.702564,32867.451282
std,1949.588546,2152.643752,1866.997511,1204.333597,1198.246371,1079.309600,1225.576630,2109.205607,2443.606788,2555.048874,...,4425.957828,3926.717747,3443.542409,3694.573544,3829.630424,4462.946328,4030.084313,4247.555161,4237.951988,91785.498686
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,1.000000,1.000000,...,28.500000,25.000000,31.000000,31.000000,36.000000,40.500000,37.500000,42.500000,45.000000,952.000000
50%,13.000000,10.000000,11.000000,12.000000,13.000000,17.000000,18.000000,26.000000,34.000000,44.000000,...,210.000000,218.000000,198.000000,205.000000,214.000000,211.000000,179.000000,233.000000,213.000000,5018.000000
75%,251.500000,295.500000,275.000000,173.000000,181.000000,197.000000,254.000000,434.000000,409.000000,508.500000,...,832.000000,842.000000,899.000000,934.500000,888.000000,932.000000,772.000000,783.000000,796.000000,22239.500000
max,22045.000000,24796.000000,20620.000000,10015.000000,10170.000000,9564.000000,9470.000000,21337.000000,27359.000000,23795.000000,...,42584.000000,33848.000000,28742.000000,30037.000000,29622.000000,38617.000000,36765.000000,34315.000000,34129.000000,691904.000000

## Checking for duplicates

Ensuring there are no duplicate rows that could affect the analysis.

In [161]:
df.duplicated().sum()

np.int64(0)

## 6. Missing Values

Checking for missing values ​​in the dataset.

In [162]:
df.isna().sum()

Country          0
Continent        0
Region           0
DevName          0
1980             0
1981             0
1982             0
1983             0
1984             0
1985             0
1986             0
1987             0
1988             0
1989             0
1990             0
1991             0
1992             0
1993             0
1994             0
1995             0
1996             0
1997             0
1998             0
1999             0
2000             0
2001             0
2002             0
2003             0
2004             0
2005             0
2006             0
2007             0
2008             0
2009             0
2010             0
2011             0
2012             0
2013             0
Total            0
Country_short    0
dtype: int64

## 7. Overview of the columns

Listing all columns for a better understanding of the dataset's characteristics.

In [163]:
df.columns

Index(['Country', 'Continent', 'Region', 'DevName', '1980', '1981', '1982',
       '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', 'Total', 'Country_short'],
      dtype='object')

## 8. Distribution of total immigration

This histogram shows how immigration values are distributed across countries.

It helps identify concentration and possible outliers.

In [164]:
df_filtered = df[df['Total'] < 100000]

fig = px.histogram(
    df_filtered,
    x='Total',
    nbins=40,
    title='Distribution of Total Immigration to Canada',
    labels={
        'Total': 'Number of Immigrants',
        'count': 'Number of Countries'
    }
)

fig.update_layout(
    title_x=0.5,
    xaxis_title='Number of Immigrants',
    yaxis_title='Number of Countries',
    template='plotly_white'
)

fig.show()

## Key insights 

This histogram shows how immigration values are distributed across countries.

To improve visualization, extreme values were filtered out, as they can distort the distribution.

Most countries contribute relatively small numbers of immigrants, while a few countries have significantly higher values.

This creates a right-skewed distribution, with a clear concentration in lower ranges and a long tail of higher values, indicating the presence of outliers.

## 9. Comparing immigration over time

This scatter plot compares immigration numbers between 1980 and 2013.

It helps identify growth patterns and country trends over time.

In [165]:
fig = px.scatter(
    df,
    x='1980',
    y='2013',
    hover_name='Country',
    color='Continent',
    title='Immigration to Canada: 1980 vs 2013'
)

fig.show()

## Key insights

This scatter plot compares immigration numbers between 1980 and 2013.

Most countries show higher immigration levels in 2013 than in 1980, indicating an overall growth trend over time.

Asian countries stand out with the highest increases, while other regions show more moderate changes.

The distribution also suggests a positive correlation between past and recent immigration levels, meaning countries with higher immigration in 1980 tend to maintain higher levels in 2013.

## 10. Top 10 Countries by Total Immigration

Analysis of the countries with the highest total number of immigrants.

This helps highlight the main contributors to immigration to Canada.

In [166]:
top_10 = df.sort_values(by='Total', ascending=False).head(10)

fig = px.bar(
    top_10,
    x='Country_short',
    y='Total',
    color='Continent',
    title='Top 10 Countries by Total Immigration to Canada'
)

fig.show()

## Key Insights

- Immigration is highly concentrated among a few countries
- There is a clear upward trend over time
- Regional differences are significant, especially in Asia

## 11. Conclusion

This analysis reveals that immigration to Canada is not evenly distributed across countries.

A small number of countries contribute disproportionately to total immigration, while most countries have relatively low numbers.

Over time, there is a clear upward trend, suggesting increasing global mobility and stronger migration flows.

These patterns highlight the importance of regional dynamics and policy impacts on immigration trends.

Further analysis could explore the socio-economic or political factors driving these patterns.